spring:
  application:
    name: JpaPaginationDemo
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: likhith
    password: likhith
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 9004